Map<String, String> en = {
  "Morning,": "Morning,",
  "Erreur": "Erreur",
  "Create the space for teams, & boost them with a happy mood":
      "Create the space for teams, & boost them with a happy mood",
  "Simple, funny, and quick,": "Simple, funny, and quick,",
  "Discover our Quiz to be the best of yourself":
      "Discover our Quiz to be the best of yourself",
  "Login": "Login",
  "Create a new account": "Create a new account",
  "Hello,": "Hello,",
  "We want to know you more": "We want to know you more",
  "Full Name": "Full Name",
  "Username": "Username",
  "Email address": "Email address",
  "Phone number": "Phone number",
  "Invalid Phone number": "Invalid Phone number",
  "Password": "Password",
  "Please accept the terms of use.": "Please accept the terms of use.",
  "Profile": "Profile",
  "Initialization Complete": "Initialization Complete",
  "Confirm your password": "Confirm your password",
  "I have a Premium access code": "I have a Premium access code",
  "Age": "Age",
  "City": "City",
  "Gender": "Gender",
  "Function": "Function",
  "By continuing the registration, I declare that I accept the terms of use":
      "By continuing the registration, I declare that I accept the terms of use",
  "Employee": "Employee",
  "Manager": "Manager",
  "Male": "Male",
  "Female": "Female",
  "Sign up": "Sign up",
  "Already have an account?": "Already have an account?",
  "Sign in": "Sign in",
  "Scrolle Left Or Right To Navigate": "Scrolle Left Or Right To Navigate",
  "Please Login to your account": "Please Login to your account",
  "Please complete all required fields": "Please complete all required fields",
  "Insert code sent to your email": "Insert code sent to your email",
  "Code": "Code",
  "Send": "Send",
  "Don’t have an account?": "Don’t have an account?",
  "Create a new one": "Create a new one",
  "Reset Password": "Reset Password",
  "Welcome back": "Welcome back",
  "Email or Mobile number": "Email or Mobile number",
  "Forgot password?": "Forgot password?",
  "Knowledge is power keep on cultivating happiness":
      "Knowledge is power keep on cultivating happiness",
  "You made it, your quiz is complete.": "You made it, your quiz is complete.",
  "Check your Report and Masterclasses": "Check your Report and Masterclasses",
  "Your report is loading": "Your report is loading",
  "you can start using the application after Sign up":
      "you can start using the application after Sign up",
  "Current Password": "Current Password",
  "New Password": "New Password",
  "Confirm your new Password": "Confirm your new Password",
  "Change": "Change",
  "Welcome ": "Welcome ",
  "It takes 2 mn to measure your happiness,":
      "It takes 2 mn to measure your happiness,",
  "you can now access all Quiz": "you can now access all Quiz",
  "Ready to boost your happiness ? here we are.":
      "Ready to boost your happiness ? here we are.",
  "Start Your Quiz": "Start Your Quiz",
  "Message": "Message",
  "Your password and confirmation password do not match":
      "Your password and confirmation password do not match",
  "The given data was invalid. !": "The given data was invalid. !",
  "Please select the answer !": "Please select the answer !",
  "I am illimited": "I am illimited",
  "I am powerful": "I am powerful",
  "I am Grateful": "I am Grateful",
  "I am focused on solutions": "I am focused on solutions",
  "I choose happiness": "I choose happiness",
  "Settings": "Settings",
  "Languages": "Languages",
  "French": "French",
  "English": "English",
  "Logout": "Logout",
  "do you want to delete ?": "do you want to delete ?",
  "Delete your account": "Delete your account",
  "not found": "Not found",
  "Choose your language": "Choose your language",
  "Do you know that a positive brain is 30% more productive ?":
      "Do you know that a positive brain is 30% more productive ?",
  "Happiness is the highest form of health":
      "Happiness is the highest form of health",
  "Happiness is determined more by one’s state of mind than by external events.":
      "Happiness is determined more by one’s state of mind than by external events.",
  " is required.": " is required.",
  "Finish": "Finish",
  "Next Question": "Next Question",
  "Get Started": "Get Started",
  "Question": "Question",
  "Now you can discover your happiness report Awareness is half of the realisation":
      "Now you can discover your happiness report Awareness is half of the realisation",
  "watch the masterclass that matches your needs":
      "watch the masterclass that matches your needs",
  "View Your Report": "View Your Report",
  "Watch Masterclasses": "Watch Masterclasses",
  "You have already passed the Quiz,stay tuned for a new one, see you soon":
      "You have already passed the Quiz,stay tuned for a new one, see you soon",
  "Browse and select from the happy  tools ":
      "Browse and select from the happy  tools ",
  "badMoodText":
      "It is ok to not to be OK \nChoose happiness and optimism no matter what \nEvery issue has solutions practice our positive affirmations \nTry a walk in nature or near your house/office \nAccept your vulnerability you are a normal human \nNothing is fixed ",
  "neutralMoodText":
      "You are in a neutral mode mood, we have some boosters for you today\n Be grateful for 3 things you have\n Check a positive podcast in our videothek\n Make a walk your mood will be better \nListen to your favorite music or our positif playlist",
  "happyMoodText":
      "Happy that you have a good mood today you will be very productive today \nKeep on this positive attitude all the week \nSpread happiness around you \nCompliment someone you care for\n List you wish/goals  list for 2023 ",
  "Terms of uses": "Terms of uses",
  "Private Notice": "Private Notice",
  "Back": "Back"
};
